add styles footer
marksavytskyi/team-project pull request #11
Opened 2022-08-28 09:33 UTC by andriideikalo

2022-08-28 12:21 UTC, marksavytskyi commented on src/partials/footer.html
> +            <form class="subscription__form">
инпут вылазит за контейнер 
![image](https://user-images.githubusercontent.com/107767178/187073923-6b9c1a71-8207-4bfa-9a2f-d3785392ad19.png)

2022-08-28 14:21 UTC, marksavytskyi commented on src/partials/footer.html
> +    <div>
<!-- зачем этот див ? -->

2022-08-28 14:22 UTC, marksavytskyi commented on src/sass/components/_footer.scss
> +  background-color: $color-white;
в body уже есть этот background-color. здесь он не нужен

2022-08-28 14:22 UTC, marksavytskyi commented on src/sass/components/_footer.scss
> +  width: 100%;
footer это block - он и так будет на всю ширину родителя. здесь width: 100% не нужен.

2022-08-28 14:22 UTC, marksavytskyi commented on src/sass/components/_footer.scss
> +    padding: 60px 0;
паддинг нужно давать на секцию .footer. и писать paddint-top, padding-bottom, ты поставил слева и справа 0 паддинг. у тебя поплыла страничка. инпут например

2022-08-28 14:23 UTC, marksavytskyi commented on src/sass/components/_footer.scss
> +    background-image: url(../images/footer/аpple__sm@1x-1.png),
эти background нужно вешать было на секцию. а не на ограниченый блок контейнером. у тебя между боковыми фоновыми изображениями еще потом 20px - смотрится не очень

2022-08-28 14:24 UTC, marksavytskyi commented on src/sass/components/_footer.scss
> +    background-size: 72px, 105px, 79px, 80px, 60px 205px, 104px 259px,
если ты выгружал картинки с макета, то они уже в нужных размерах. не уверен что тут нужен background size

2022-08-28 14:25 UTC, marksavytskyi commented on src/sass/components/_footer.scss
> +    padding-left: 53%;
тут маржин, а не паддинг

2022-08-28 14:25 UTC, marksavytskyi commented on src/sass/components/_footer.scss
> +    margin-bottom: 73px;
этот маржин не от элемента, а от секции надо делать. в этом случае от footer__nav

2022-08-28 14:26 UTC, marksavytskyi commented on src/sass/components/_footer.scss
> +    text-decoration: none;
text-decoration ничего не делает здесь

2022-08-28 14:26 UTC, marksavytskyi commented on src/sass/components/_footer.scss
> +    font-family: "Roboto";
font-family в body прописан, эта строка лишняя

2022-08-28 14:26 UTC, marksavytskyi commented on src/sass/components/_footer.scss
> +    font-style: normal;
font-style в нормализаторе есть, тоже ничего не делает эта строка

2022-08-28 14:27 UTC, marksavytskyi commented on src/sass/components/_footer.scss
> +    font-weight: 400;
font-weight: 400 в body прописан как базовый стиль

2022-08-28 14:27 UTC, marksavytskyi commented on src/sass/components/_footer.scss
> +    width: 69px;
высота и ширина не нужна, ты ее указал на <svg> в html

2022-08-28 14:28 UTC, marksavytskyi commented on src/sass/components/_footer.scss
> +    display: block;
больше подойдет inline-block

2022-08-28 14:28 UTC, marksavytskyi commented on src/sass/components/_footer.scss
> +  &__input {
инпут выпирает за границу контейнера, что-то вылазит. указывал выше из-за чего

2022-08-28 14:29 UTC, marksavytskyi commented on src/sass/components/_footer.scss
> +    min-width: 103px;
тут просто width

2022-08-28 14:29 UTC, marksavytskyi commented on src/sass/components/_footer.scss
> +    border: none;
зачем тут бордер нон, если на след. строке ты перебиваешь его и даешь бордер?

2022-08-28 14:29 UTC, marksavytskyi commented on src/sass/components/_footer.scss
> +    color: $color-black-primary;
цвет в body указан

2022-08-28 14:30 UTC, marksavytskyi commented on src/sass/components/_footer.scss
> +    margin-bottom: 60px;
отступать от блока нужно блоком. margin-bottom должен быть на footer__menu

2022-08-28 14:31 UTC, marksavytskyi commented on src/sass/components/_footer.scss
> +  &__input {
![image](https://user-images.githubusercontent.com/107767178/187079269-74b3b7cd-318b-449a-bc61-2e84216a4a6d.png)

2022-08-28 14:32 UTC, marksavytskyi commented on src/sass/components/_footer.scss
> +    background-image: url(../images/footer/аpple__sm@1x-1.png),
![image](https://user-images.githubusercontent.com/107767178/187079350-b4e8534b-df1a-499b-909a-ac1c583e6748.png)

2022-08-28 14:33 UTC, marksavytskyi commented on src/sass/components/_footer.scss
> +    background-image: url(../images/footer/аpple__sm@1x-1.png),
ну и здесь брызги не под тем углом

2022-08-28 14:33 UTC, marksavytskyi requested changes
go

2022-08-28 15:30 UTC, andriideikalo commented on src/sass/components/_footer.scss
> +    border: none;
рабочие моменты. не убрал)

2022-08-28 15:30 UTC, andriideikalo commented on src/sass/components/_footer.scss
> +    color: $color-black-primary;
убрал

2022-08-28 15:30 UTC, andriideikalo commented on src/sass/components/_footer.scss
> +    margin-bottom: 60px;
сделал

2022-08-28 15:31 UTC, andriideikalo commented on src/sass/components/_footer.scss
> +    min-width: 103px;
поправил

2022-08-28 15:31 UTC, andriideikalo commented on src/sass/components/_footer.scss
> +  &__input {
поправил

2022-08-28 15:33 UTC, andriideikalo commented on src/sass/components/_footer.scss
> +    display: block;
не принципиально. можно и блок

2022-08-28 15:34 UTC, andriideikalo commented on src/sass/components/_footer.scss
> +    width: 69px;
не люблю в html размеры. тоже рабочие моменты

2022-08-28 15:35 UTC, andriideikalo commented on src/sass/components/_footer.scss
> +    font-weight: 400;
убрал.

2022-08-28 15:36 UTC, andriideikalo commented on src/sass/components/_footer.scss
> +    font-style: normal;
на автомате прописываю. не привык ещё))

2022-08-28 15:36 UTC, andriideikalo commented on src/sass/components/_footer.scss
> +    font-family: "Roboto";
на автомате)

2022-08-28 15:38 UTC, andriideikalo commented on src/sass/components/_footer.scss
> +    text-decoration: none;
когда писал стили были подчеркивания. хз почему.

2022-08-28 15:43 UTC, andriideikalo commented on src/sass/components/_footer.scss
> +    padding-left: 53%;
ok

2022-08-28 15:45 UTC, andriideikalo commented on src/sass/components/_footer.scss
> +    background-size: 72px, 105px, 79px, 80px, 60px 205px, 104px 259px,
конечно с макета, но размеры не те. мажет на весь экран. сам удивился....

2022-08-28 15:47 UTC, andriideikalo commented on src/sass/components/_footer.scss
> +    background-image: url(../images/footer/аpple__sm@1x-1.png),
тут проблема. ставлю трансформ, поворачивает все элементы

2022-08-28 15:48 UTC, andriideikalo commented on src/sass/components/_footer.scss
> +    padding: 60px 0;
переставил

2022-08-28 15:51 UTC, andriideikalo commented on src/partials/footer.html
> +    <div>
шо це?

2022-08-28 15:52 UTC, andriideikalo commented on src/partials/footer.html
> +            <form class="subscription__form">
уже пофиксил

2022-08-29 12:34 UTC, marksavytskyi commented on src/partials/footer.html
> +        <nav class="footer__nav">
большой маржин ботом 

![image](https://user-images.githubusercontent.com/107767178/187201975-5e9c2655-44b7-4951-b14a-68335e88ab67.png)

2022-08-29 12:39 UTC, marksavytskyi commented on src/partials/footer.html
> +            <label for="subscribe" class="subscription__title"
у тебя тут font-weight: 600, а в макете 500

2022-08-29 12:41 UTC, marksavytskyi commented on src/partials/footer.html
> +              <input
при invalid у тебя под кнопкной warning текст должен быть
![image](https://user-images.githubusercontent.com/107767178/187203418-b4513dda-1cf8-4167-b28e-2a47c57b9c9f.png)

2022-08-29 12:44 UTC, marksavytskyi commented on src/partials/footer.html
> +                class="subscription__input"
width: 100%

2022-08-29 12:50 UTC, marksavytskyi requested changes
исправь это и всё ок

2022-08-29 17:31 UTC, closed without merging